### ISSUE TITLE
不允许使用认证服务来认证您访问的目标应用

### ISSUE THREAD

**Issue by Asakeii** [parsifal486/QduLibrarySeatBooking#1]
请问访问网页提示“应用未注册：不允许使用认证服务来认证您访问的目标应用。”该如何解决

**Comment by parsifal486** [comment]
对不起呀!图书馆预约的样式好像之前那段时间是变化了的,我没来得及做新的适配,因为现在图书馆座位蛮好占的所以我就没再维护拉,实在不好意思555
